name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can use other environments too, e.g., macos-latest

    steps:
      - uses: actions/checkout@v4  # Checkout your repo code
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Set Python version
      - run: python -m venv .venv && source .venv/bin/activate  # Setup virtual environment
      - run: pip install -r requirements.txt  # Install dependencies
      - run: pip install pytest  # Install testing library
      - run: pytest tests/  # Run your tests

      # Run the actual project code (headless test for Tkinter)
      - name: Run wallet recovery app (headless)
        run: |
          # Here we simulate running the Tkinter GUI in headless mode
          python -m src.gui  # Adjust to your entry point
        env:
          DISPLAY: :99  # Display variable for headless mode

      # Optionally, you can also check for log file or output from running the app
      - name: Check GUI output (logs)
        run: cat output.log || echo "No output generated."
